### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by jaikishantulswani** [mk13337/gowitness_reporter#1]
@mk13337 do we need to change the name of the gowitness_reporter folder to `app` or can you please show the clear instructions to run this after running gowitness server

**Comment by mk13337** [comment]
Hi!
I recommend using docker: https://github.com/mk13337/gowitness.
This option is the easiest and most convenient.

However, if you want to run the project separately, here are the instructions:
1) Clone mk13337/gowitness_reporter
2) Install chromium (if it wasn't installed before): `apt install chromium`.
3) cd into dir and download original gowitness binary: `wget https://github.com/sensepost/gowitness/releases/download/2.5.1/gowitness-2.5.1-linux-amd64 -O gowitness; chmod +x gowitness`.
4) Create file with urls and start gowitness: `./gowitness file -f urls.txt`.
5) Run gowitness in report mode `./gowitness report serve`
6) While gowitness is running, from another window, run main.py: `python3 main.py`.

In the gowitness_reporter directory you will find the result, three files: gallery.html, table.html, perception.html
